name: SnowyTeams
version: '1.0-B1'
main: dev.snowy.SnowyTeams
api-version: '1.20'
authors: ["okgsss"]
website: "https://discord.gg/jAF8R8MKE4"
description: The best teams plugin for minecraft
depend: ["PlaceholderAPI", "Vault"]
commands:
  clan:
    description: Comando principal para la gestión de clanes.
    aliases: ["team"]
  clanadmin:
    description: Comando principal para la administración de clanes.
    aliases: ["teamadmin"]